# Generated by Django 2.2 on 2019-08-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_todo_date_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_event',
            field=models.DateField(),
        ),
    ]
